//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoldFit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forma
    {
        public int id { get; set; }
        public string WymiarA { get; set; }
        public string WymiarB { get; set; }
        public string WymiarC { get; set; }
        public Nullable<int> ProjektId { get; set; }
    
        public virtual ProjektTest ProjektTest { get; set; }
    }
}
